services:
  opensearch:
    image: opensearchproject/opensearch:latest@sha256:22fdee0d6db3f500a64cd27ddff3633f32244d0ea58b68ffb151cd2217f0bb0d
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=123849password!P
    ports:
      - "9200:9200"
    networks:
      - proxy

  opensearch-filter-proxy:
    image: opensearch-filter-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENSEARCH_URL: http://opensearch:9200
      RUST_LOG: info
    ports:
        - "3000:3000"
    networks:
      - proxy

networks:
  proxy:
