services:
  opensearch:
    image: opensearchproject/opensearch:latest@sha256:2f2244c7c0ad3a4a0d09977c2b519977b77bacc92e1eaf995c080c1d22f517b6
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=123849password!P
    ports:
      - "9200:9200"
    networks:
      - proxy

  opensearch-filter-proxy:
    image: opensearch-filter-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENSEARCH_URL: http://opensearch:9200
      RUST_LOG: info
    ports:
        - "3000:3000"
    networks:
      - proxy

networks:
  proxy:
